name: 'Modules Test Run - OpenTofu Latest'

on:
  schedule:
    - cron: '0 8 * * 5' # run every Friday at 11:00 MSK
  workflow_dispatch:

jobs:
  setup:
    name: 'Modules Test Run - OpenTofu Latest'
    runs-on: self-hosted
    env:
      TF_VAR_selectel_domain_name: ${{ secrets.SELECTEL_DOMAIN_NAME }}
      TF_VAR_selectel_user_name: ${{ secrets.SELECTEL_USER_NAME }}
      TF_VAR_selectel_user_id: ${{ secrets.SELECTEL_USER_ID }}
      TF_VAR_selectel_user_password: ${{ secrets.SELECTEL_USER_PASSWORD }}
      TF_VAR_selectel_project_name: ${{ secrets.SELECTEL_PROJECT_NAME }}
      TF_VAR_selectel_project_id: ${{ secrets.SELECTEL_PROJECT_ID }}
      TF_VAR_flavor_name: ${{ secrets.FLAVOR_NAME }}
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1

    - name: Add .tofurc
      shell: bash
      run: |
        cat <<EOS >> $HOME/.tofurc
        provider_installation {
            network_mirror {
              url = "https://tf-proxy.selectel.ru/mirror/v1/"
            }
        }
        EOS

    - name: Lint OpenTofu
      run: tofu fmt -diff -check -recursive

    - name: Init OpenTofu
      run: >
        tofu init -reconfigure
        -backend-config="bucket=github-terraform-state"
        -backend-config="key=github-infra-examples.tfstate"
        -backend-config="access_key=${{ secrets.S3_ACCESS_KEY }}"
        -backend-config="secret_key=${{ secrets.S3_SECRET_KEY }}"

    - name: OpenTofu apply
      run: tofu apply -auto-approve

    - name: OpenTofu destroy
      run: tofu destroy -auto-approve

    - name: Send Telegram alert if failed on the main branch
      if: ${{ (failure()) && (github.ref == 'refs/heads/main') }}
      uses: cbrgm/telegram-github-action@v1
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        thread-id: 168
        message: |
          ⚙️ GitHub repository selectel/selectel-infra-examples

          🔥 OpenTofu pipeline has failed!
          ➡️ Workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}